upstream api_upstream {
  server api-service.ip-reputation.svc.cluster.local:8000;
}
upstream auth_upstream {
  server auth-service.ip-reputation.svc.cluster.local:8001;
}

server {
  listen 80 default_server;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  # SPA
  location / { try_files $uri /index.html; }

  # Clean route: /api/check-ip/<ip>  ->  /auth/check-reputation/<ip> (auth service)
  location ~ ^/api/check-ip/(.*)$ {
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header Connection        "";
    proxy_pass http://auth_upstream/check-reputation/$1;
  }

  # General API to api-service
  location /api/ {
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header Connection        "";
    proxy_pass http://api_upstream/;
  }

  # Auth routes
  location /auth/ {
    proxy_http_version 1.1;
    proxy_set_header Host              $host;
    proxy_set_header X-Real-IP         $remote_addr;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header Connection        "";
    proxy_pass http://auth_upstream/;
  }
}