apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: ip-reputation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: ntvs28/ip-reputation-checker-auth-service:v3-20250927203821
        ports:
        - containerPort: 8001
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/ip_reputation_db
        - name: JWT_SECRET_KEY
          value: "your-super-secret-key-change-this-in-production"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:30080,http://127.0.0.1:30080"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: ip-reputation
spec:
  selector:
    app: auth-service
  ports:
  - port: 8001
    targetPort: 8001
