apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: ip-reputation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ntvs28/ip-reputation-checker-api-service:v-api-20250927174753
        ports:
        - containerPort: 8000
        env:
        - name: ANALYSIS_URL
          value: http://analysis-service:8002
        - name: AUTH_URL
          value: http://auth-service:8001
        - name: JWT_SECRET_KEY
          value: "your-super-secret-key-change-this-in-production"
        - name: ALLOWED_ORIGINS
          value: "http://localhost:30080,http://127.0.0.1:30080"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ip-reputation
spec:
  selector:
    app: api-service
  ports:
  - port: 8000
    targetPort: 8000
