apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: ip-reputation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend
        image: ntvs28/ip-reputation-checker-frontend-web:v-ui-20250927205653
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-web
  namespace: ip-reputation
spec:
  type: NodePort
  selector:
    app: frontend-web
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
